### PR TITLE
added offline functionality for update & delete

### PR DESCRIPTION
**Pull request by protibimbok**

### CODE REVIEW

**Comment by permafrost06** [comment]
This pr seems to use `localstorage` still. I thought we were trying to figure out if an alternative solution (e.g. sqlite in browser) would be better for our case. Please justify.

**Comment by protibimbok** [comment]
I've used localstorage as it was already implemented, to finish the caching for existing apis. If I switched to SQLite(if possible) right now it'd be a bit messy because this feature is not directly available. I'd had to focus on two different aspects: the SQLite & how it plays with the frontend code. I've somewhat completed the second part so that when we shift to SQLite, it becomes easier (just replacing the localstorage calls with SQLite ones).

**Comment by permafrost06** [comment]
Okay, merging this for now, but we'll have to test and decide on a feasible offline strategy going forward. Until then, work on offline functionality is paused.

**Review by permafrost06 — APPROVED** [review]
Okay, merging this for now, but we'll have to test and decide on a feasible offline strategy going forward. Until then, work on offline functionality is paused.

**Pull request merged**
