### PR TITLE
Add pagination component

### PR DESCRIPTION
**Pull request by protibimbok**
Only local items pagination is supported now.

### CODE REVIEW

**Review by permafrost06 — COMMENTED** [review]
How do you expect to implement server side pagination with the current approach?

**Comment by protibimbok** [comment]
We'll take the necessary props and fetch the data.
```typescript
interface Pagination {
    url: string | ((page: number) => string),
    queryParams: Record<string, string>
}
```
This is just an example...

**Comment by permafrost06** [comment]
What if we need to do auth for some data, and not for others? How would we handle that?

**Comment by protibimbok** [comment]
If you mean `some data` as some api `endpoint` then we can take an additional prop named `reqHeaders` where all of the authentication headers will be passed.
If you mean other things, please give me complete scenario and/or testcase.

**Comment by permafrost06** [comment]
This will get really complicated really fast. Fetching data is not the concern of the pagination component as requirements can vary widely. This PR will not be merged. Please stick to the requirements described in #22.

**Pull request closed without merging**
