### PR TITLE
Added styling to the table component

### PR DESCRIPTION
**Pull request by protibimbok**

### CODE REVIEW

**Review by permafrost06 — COMMENTED** [review]
We will try not to use scoped styles unless necessary. They are quite overused and, in my opinion, prevents writing good CSS.

**Comment by protibimbok** [comment]
I am a bit confused right now. A detailed guideline over when to use scoped and when not to would be great.

**Comment by permafrost06** [comment]
My problem basically comes down to this: scoped styles are not available everywhere (I mean while working on other projects) and can instill bad habits for beginners.

When we're using scoped styles, we don't have to worry about other components. This results in styles that are bound to tags, and not classes. This is not standard practice - especially where scoped styles are not available. Therefore, class naming and overall CSS structuring skills are left under-developed while using scoped styles.

Why should we re-train our brains to read styles differently just because we have scoped styles in this project? We should use universal CSS best practices unless there's a good reason for going against it. Do you have any such argument for using scoped styles in this case, or are you using it because you have the option to use it?

That doesn't mean we should totally forgo scoped styles; it is yet another tool in our problem solving toolbox. If we have an issue that can be easily resolved using scoped styles, we should go for it, by all means.

I hope this clears up your confusion.

**Review by permafrost06 — APPROVED** [review]

**Comment by protibimbok** [comment]
I understand your problem. But when I moved all the styles to global CSS you told me this was not what you had meant. That's where I am confused. Do you mean we should use utility classes?

**Comment by permafrost06** [comment]
Utility classes are not required here. I meant that we should add classes (unique to the component, maybe namespaced, so that does not conflict with other styles in the project) to the elements we want to style and style the classes instead of elements/tags. So, instead of

```css
table {
    border-collapse: separate;
    border-spacing: 0 4px;
}
```

We can add a class "table-inner" to the `table` element and write

```css
.table-wrapper .table-inner {
    border-collapse: separate;
    border-spacing: 0 4px;
}
```

With SCSS, we can effectively do namespaces:

```scss
.table-wrapper {
    .table-inner {
        border-collapse: separate;
        border-spacing: 0 4px;
    }
}
```

**Pull request merged**
